import os
import tempfile
from typing import List, Optional
from pptx import Presentation
from pptx.util import Inches

# Placeholder for Agno agents
# This is where the user's Agno orchestrator code would go
# For now, a simple PPT generator

def orchestrate(topic: str, criteria_list: List[str], agent_context: Optional[str] = None):
    """
    Orchestrate the PPT generation using Agno agents.
    Returns: (ppt_file_path, qc_results)
    """
    # Create a temporary PPT file
    with tempfile.NamedTemporaryFile(suffix='.pptx', delete=False) as tmp:
        ppt_file = tmp.name

    # Create presentation
    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = topic
    subtitle.text = "Generated by Agno Orchestrator"

    # Content slides based on criteria
    bullet_slide_layout = prs.slide_layouts[1]
    for i, criterion in enumerate(criteria_list[:5]):  # Limit to 5 slides
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]

        title_shape.text = f'Slide {i+1}'
        tf = body_shape.text_frame
        tf.text = criterion

        # Add some bullets
        p = tf.add_paragraph()
        p.text = "Point 1"
        p.level = 1
        p = tf.add_paragraph()
        p.text = "Point 2"
        p.level = 1

    # Save the presentation
    prs.save(ppt_file)

    # Mock QC results
    qc_results = []
    for criterion in criteria_list:
        qc_results.append({
            "criterion": criterion,
            "result": "pass",  # or "fail"
            "reason": "Mock QC check passed"
        })

    return ppt_file, qc_results
